CONFIRM_EMAIL = 1
CHANGE_PASSWORD = 2
PAGE_SIZE = 50  # Если меняешь здесь, меняй в load_things.js в функции main и my_books_load.js в функции _main
TARGET_EDITION = 1
TARGET_BOOK = 2
TARGET_STUDENT = 3
TARGET_WAITING_STUDENTS = 4
Librarian = 'Librarian'
Student = 'Student'
WaitingStudent = 'WaitingStudent'
